/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.mcgill.ecse.flexibook.application;

import java.awt.EventQueue;
import java.io.File;
import java.sql.Date;
import java.sql.Time;

import ca.mcgill.ecse.flexibook.model.FlexiBook;
import ca.mcgill.ecse.flexibook.model.User;
import ca.mcgill.ecse.flexibook.persistence.FlexiBookPersistence;
import ca.mcgill.ecse.flexibook.view.UIPage;

public class FlexiBookApplication {
    private static FlexiBook flexibook;
    private static User currentUser;
    private static Date currentDate;
    private static Time currentTime;
    private static String filename = "testdata.flexibook";
    private static boolean testMode = false;

    public static FlexiBook getFlexiBook() {

        if (flexibook == null) {
            flexibook = FlexiBookPersistence.load();
        }

        return flexibook;
    }

    public static void setTestMode(boolean a) {
        testMode = a;
    }

    public static void setCurrentUser(User user) {
        currentUser = user;
    }

    public static User getCurrentUser() {
        return currentUser;
    }

    public static void setCurrentDate(Date Date) {
        currentDate = Date;
    }

    public static void setCurrentTime(Time Time) {
        currentTime = Time;
    }

    public static Date getCurrentDate() {
        if (testMode) {
            return currentDate;
        } else {
            // add system time and date here
            long timeStamp = System.currentTimeMillis();
            return new java.sql.Date(timeStamp);
        }
    }

    public static Time getCurrentTime() {
        if (testMode) {
            return currentTime;
        } else {
            //add system time and date here
            long timeStamp = System.currentTimeMillis();
            return new java.sql.Time(timeStamp);
        }
    }

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        FlexiBookPersistence.setFilename(filename);
        // remove test file
      // File f = new File(filename);
      //	f.delete();
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIPage window = new UIPage();
                    window.frmFlexibook.setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }
}
